### ISSUE TITLE
fix all abort / exit / stderr / stdout statements

### ISSUE THREAD

**Issue by jwijffels** [bnosac/audio.whisper#1]

**Comment by ggerganov** [comment]
I think you can make this change simpler via macros.
For example, you can put this near the top of the file to avoid all `fprintf > Rprintf` changes:

```c
#define fprintf(dummy, ...) Rprintf(__VA_ARGS__)
```

**Comment by jwijffels** [comment]
Thanks for looking upstream in this repository. I'll take your advice on the macro's so that upgrading to another release of whisper.cpp will be more easy.
