### ISSUE TITLE
Transcript to French

### ISSUE THREAD

**Issue by CharlyMarie** [bnosac/audio.whisper#11]
Hi,

Congrats for the awesome work !

When using predict on a French speaking audio, I get weird typos such as "Ca rÃ¨gle un sacrÃ© problÃ¨me" which should be "Ca règle un sacré problème."

Could I solve this encoding problem ?

Thanks !

**Comment by jwijffels** [comment]
Do you mean the output of predict or the printout you see during the transcription.
The output of thf predict is set to utf8 in https://github.com/bnosac/audio.whisper/blob/master/R/whisper.R#L31
The printing itself during the transcription process is coming from the Rcpp side.

**Comment by CharlyMarie** [comment]
Thanks to your feedback, there is a way to extract it in the right typo : 

df <- as.data.frame(trans[["data"]][["text"]])
df$`trans[["data"]][["text"]]` <- iconv(df$`trans[["data"]][["text"]]`, from="UTF-8", to="LATIN1")

df1 <- as.data.frame(paste(unlist(df), collapse =" "))
audio <- df1$`paste(unlist(df), collapse = " ")`[]

Careful though, GitHub hides the ' in my coding and interprets it as code, if anyone wishes to reproduce it.

**Comment by jwijffels** [comment]
Probably you just meant to do 

```
library(audio.whisper)
model <- whisper("tiny")
audio <- system.file(package = "audio.whisper", "samples", "jfk.wav")
trans <- predict(model, newdata = audio)
trans[["data"]][["text"]] <- iconv(trans[["data"]][["text"]], from="UTF-8", to="LATIN1")
```
