### ISSUE TITLE
Unable to transcribe on Linux

### ISSUE THREAD

**Issue by carlganz** [bnosac/audio.whisper#12]
```
predict(whisper_model, newdata="inst/demo_recording.wav", language = "en")
```
[demo_recording.zip](https://github.com/bnosac/audio.whisper/files/10972836/demo_recording.zip)

Works perfectly on Windows, but on latest Ubuntu I get an inscrutable error: `Error: tinyformat: Not enough conversion specifiers in format string`

Any guidance would be greatly appreciated

**Comment by jwijffels** [comment]
is that a wav file?

**Comment by carlganz** [comment]
[demo_recording.zip](https://github.com/bnosac/audio.whisper/files/10973178/demo_recording.zip)

Yes I sent wrong file apologies

**Comment by jwijffels** [comment]
The wav file you are sending is not a 16-bit wav file

```
> library(av)
> av_media_info("C:/Users/jwijf/OneDrive/Bureaublad/demo_recording.wav")
$duration
[1] 24.64

$video
NULL

$audio
  channels sample_rate     codec frames bitrate     layout
1        1        8000 pcm_s16le     NA  128000 1 channels
```

**Comment by carlganz** [comment]
Interesting. Changing sampling rate did the trick. Surprised it worked at all on Windows.

I would strongly encourage adding some sort of input validation with clearer error messages.

Thank you for the quick response and helpful package.
