### ISSUE TITLE
Can't load models from small and above

### ISSUE THREAD

**Issue by sebsilas** [bnosac/audio.whisper#16]
I am not able to load a model from small and above ("whisper_init: failed to load model"), even though I appear to have good enough hardware settings to run all the models. I'm running a 2,4 Ghz 8-Core Intel Core Macbook Pro with 32GB RAM and using the latest stable release of `whisper.audio` (0.2.1).

Here is the output when I try and load the e.g., small model:

```
whisper_init_from_file: loading model from '/Users/sebsilas/project/data-raw/ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 3
whisper_model_load: mem required  =  603.00 MB (+   16.00 MB per decoder)
whisper_model_load: kv self size  =   15.75 MB
whisper_model_load: kv cross size =   52.73 MB
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  464.56 MB
whisper_model_load: model size    =  204.65 MB
whisper_model_load: ERROR not all tensors loaded from model file - expected 479, got 165
whisper_init: failed to load model
```

I don't think this is an R memory limit issue:

```
> unix::rlimit_all()$cur
     as    core     cpu    data   fsize memlock  nofile   nproc   stack 
    Inf       0     Inf     Inf     Inf     Inf   10496    5568 8388608 
```

How can I overcome this?

**Comment by jwijffels** [comment]
This happened to me once when the model download only was run partially, due to a bad network/wifi connection.

**Comment by sebsilas** [comment]
The small model was 204.2 Mb. But, I tried downloading again and now the model is 465 Mb and loads appropriately!

I'll try with the even larger models again.

Maybe worth noting this on the main package page.

I was just running things like this:

```
sml <- whisper("small")
```

So i guess it's using `whisper_model_load`, to answer your question.

**Comment by jwijffels** [comment]
Good to know. R function whisper is just a tiny wrapper around `whisper_download_model ` and `whisper_load_model` as can be seen here: https://github.com/bnosac/audio.whisper/blob/master/R/whisper.R#L88-L100
Once you have the model, you can just use `whisper_load_model `providing the path to the model.

**Comment by sebsilas** [comment]
I meant maybe it's worth noting that the model downloading could produce the error that I experienced, given that it's something that seems to be relatively common.

Also, to add. I've tried about 10 times now to download the large model and it hasn't worked, with very variable download sizes, and I still haven't had a successful result. Maybe there is a better way to download the model? I haven't generally had an issue with this kind of thing before.

**Comment by jwijffels** [comment]
I'm sorry, this R package does not provide the models. They are hosted at https://huggingface.co/datasets/ggerganov/whisper.cpp or https://ggml.ggerganov.com, the whisper_download_model is providing an easy way to download it. If you have a bad network/wifi, just download the models manually.

**Comment by sebsilas** [comment]
I've downloaded the model, but `whisper_load_model` is not exported in the package.

**Comment by jwijffels** [comment]
Right, I meant, provide the path to the model with function `whisper `as documented in the help.
