### ISSUE TITLE
URLs hard-coded in the model download package are incorrect

### ISSUE THREAD

**Issue by prolabrus** [bnosac/audio.whisper#18]
Please update the links - all URLs hard-coded in the model download package are incorrect.

**Comment by jwijffels** [comment]
@prolabrus You can download the models from https://huggingface.co/ggerganov/whisper.cpp/commit/80da2d8bfee42b0e836fc3a9890373e5defc00a6 and next pass the path to the file where you stored the model to the function whisper.

> library(audio.whisper)
> model <- whisper("inst/model-repository/ggml-small.bin")
whisper_init_from_file: loading model from 'inst/model-repository/ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 3
whisper_model_load: mem required  =  603.00 MB (+   16.00 MB per decoder)
whisper_model_load: kv self size  =   15.75 MB
whisper_model_load: kv cross size =   52.73 MB
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  464.56 MB

@MrFlick I don't known if the newer models are compatible with version 0.2.1 of this R package which is built on top of the Stable whisper.cpp version v1.2.1 (v1.4.2 is still beta)
I'll upgrade the bindings once tinydiarize is incorporated in whisper.cpp

**Comment by jwijffels** [comment]
I've updated the URL's for repos = "huggingface" and deprecated the repos = "ggerganov" as some models are no longer available at this last location.
This should have fixed this issue.
