### ISSUE TITLE
Problems with the version of audio.whisper

### ISSUE THREAD

**Issue by SebastianPereyra** [bnosac/audio.whisper#19]
I want to use this package (audio.whisper) in RStudio but I can’t install it. When trying to install it, RStudio tells me that the package is not compatible with the version of R. It is important to mention that the version of R I have is 2023-03 for Windows. Is there any way to solve this problem?
Thank you!

**Comment by jwijffels** [comment]
Can you show the command and output of installing the package.

**Comment by SebastianPereyra** [comment]
install.packages("audio.whisper")

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/41698173/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘audio.whisper’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by jwijffels** [comment]
did you read the README on how to install the package? https://github.com/bnosac/audio.whisper#installation

**Comment by SebastianPereyra** [comment]
> remotes::install_github("bnosac/audio.whisper", ref = "0.2.1-1")
Error in loadNamespace(x) : there is no package called ‘remotes’
> install.packages("remotes")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/xxxxx/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/remotes_2.4.2.1.zip'
Content type 'application/zip' length 399175 bytes (389 KB)
downloaded 389 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xxxxxxx\AppData\Local\Temp\RtmpYlzZtb\downloaded_packages

**Comment by jwijffels** [comment]
> Package audio.whisper has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
> Install Rtools ([https://cran.r-project.org/bin/windows/Rtools/)](https://cran.r-project.org/bin/windows/Rtools/).Then)

**Comment by SebastianPereyra** [comment]
thanks a lot. It works great!
