### ISSUE TITLE
Error when loading model

### ISSUE THREAD

**Issue by azoezoe** [bnosac/audio.whisper#22]
Hello,

When using this package on my Macbook M1, RStudio crashes when executing `model <- whisper("medium")` . 
I have confirmed that there are no issues with the model's binary files (as it runs fine on other computers). 
Upon inspecting the code, it appears to crash when comes to `whisper_model_load: mem required = 1720.00 MB (+ 43.00 MB per decoder)` ,and it does not complete the following lines: 
```
whisper_model_load: kv self size = 42.00 MB 
 whisper_model_load: kv cross size = 140.62 MB
 whisper_model_load: adding 1608 extra tokens
 whisper_model_load: model ctx = 1462.35 MB
 whisper_model_load: model size = 1462.12 MB.
```

**Comment by jwijffels** [comment]
I don't have a Macbook M1 but some questions

- how did you install the package
- does the tiny model work
- how many ram does your computer have

**Comment by azoezoe** [comment]
- how did you install the package
I tried two ways to install it, but neither was successful.
`remotes::install_github("bnosac/audio.whisper", ref = "0.2.1-1")`
`remotes::install_github("bnosac/audio.whisper")`

- does the tiny model work
No. None of model work.

- how many ram does your computer have
8GB

- did you use any of the compilation flags for Mac as outlined here
Can I confirm by just pasting the code into the terminal? Because I paste it and it shows some errors.

It works well on my another macbook (not M1), and I found that there are also some issues [here]("https://github.com/openai/whisper/discussions/categories/general?discussions_q=is%3Aopen+category%3AGeneral+M1") regarding using whisper with M1 computers. I will confirm them. Thank you for your reply.

**Comment by jwijffels** [comment]
Can you show the log of `remotes::install_github("bnosac/audio.whisper", ref = "0.2.1-1")`

> Can I confirm by just pasting the code into the terminal? Because I paste it and it shows some errors.

No you can not, you need to find out which macos (Darwin or powerpc) related settings are listed up. Probably the ones at 
```
# Mac M1 - include Accelerate framework
	ifeq ($(UNAME_S),Darwin)
		CFLAGS  += -DGGML_USE_ACCELERATE
		LDFLAGS += -framework Accelerate
	endif
```
Next, pull the repository and change the src/Makevars (https://github.com/bnosac/audio.whisper/blob/master/src/Makevars) appropriately for your hardware and installt the package again and load the model.

**Comment by azoezoe** [comment]
It's work 😭
But I am not sure which way make it work, I run `remotes::install_github("bnosac/audio.whisper", ref = "0.2.1-1")` and pull the repository and change the src/Makevars. 

Thank you again!

By the way, here is the log of `remotes::install_github("bnosac/audio.whisper", ref = "0.2.1-1")`
`remotes::install_github("bnosac/audio.whisper", ref = "0.2.1-1")
Downloading GitHub repo bnosac/audio.whisper@0.2.1-1
✔  checking for file ‘/private/var/folders/mn/qz3m19yn1cz1jbphrjwpmnmm0000gn/T/Rtmp1GYn8O/remotes32eb3fabf867/bnosac-audio.whisper-64a0eaf/DESCRIPTION’ (528ms)
─  preparing ‘audio.whisper’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘audio.whisper_0.2.1-1.tar.gz’
   
* installing *source* package ‘audio.whisper’ ...
** using staged installation
** libs
rm -f audio.whisper.so whisper_cpp/ggml.o whisper_cpp/whisper.o   whisper_cpp/common.o   rcpp_whisper.o   RcppExports.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -pthread -DSTRICT_R_HEADERS -I./dr_libs -I./whisper_cpp  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c whisper_cpp/ggml.c -o whisper_cpp/ggml.o
whisper_cpp/ggml.c:1400:20: warning: unused function 'ggml_is_vector' [-Wunused-function]
static inline bool ggml_is_vector(const struct ggml_tensor * tensor) {
                   ^
whisper_cpp/ggml.c:1406:20: warning: unused function 'ggml_is_matrix' [-Wunused-function]
static inline bool ggml_is_matrix(const struct ggml_tensor * tensor) {
                   ^
whisper_cpp/ggml.c:1412:20: warning: unused function 'ggml_can_mul_mat' [-Wunused-function]
static inline bool ggml_can_mul_mat(const struct ggml_tensor * t0, const struct ggml_tensor * t1) {
                   ^
whisper_cpp/ggml.c:1431:20: warning: unused function 'ggml_is_padded_1d' [-Wunused-function]
static inline bool ggml_is_padded_1d(const struct ggml_tensor * tensor) {
                   ^
whisper_cpp/ggml.c:1451:20: warning: unused function 'ggml_can_repeat' [-Wunused-function]
static inline bool ggml_can_repeat(const struct ggml_tensor * t0, const struct ggml_tensor * t1) {
                   ^
whisper_cpp/ggml.c:1465:19: warning: unused function 'ggml_up64' [-Wunused-function]
static inline int ggml_up64(int n) {
                  ^
6 warnings generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -pthread -DSTRICT_R_HEADERS -I./dr_libs -I./whisper_cpp  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c whisper_cpp/whisper.cpp -o whisper_cpp/whisper.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -pthread -DSTRICT_R_HEADERS -I./dr_libs -I./whisper_cpp  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c whisper_cpp/common.cpp -o whisper_cpp/common.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -pthread -DSTRICT_R_HEADERS -I./dr_libs -I./whisper_cpp  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c rcpp_whisper.cpp -o rcpp_whisper.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -pthread -DSTRICT_R_HEADERS -I./dr_libs -I./whisper_cpp  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o audio.whisper.so whisper_cpp/ggml.o whisper_cpp/whisper.o whisper_cpp/common.o rcpp_whisper.o RcppExports.o -pthread -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-audio.whisper/00new/audio.whisper/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (audio.whisper)`

**Comment by jwijffels** [comment]
If this is the compilation trace log you are using, it doesn't look like you have changed the Makevars settings to something like below before installing the package

PKG_CPPFLAGS = -pthread -DSTRICT_R_HEADERS -I./dr_libs -I./whisper_cpp -framework Accelerate
PKG_CFLAGS = -DGGML_USE_ACCELERATE

**Comment by jwijffels** [comment]
Closing as you indicated it works.
